---
title: "exploratory"
author: "Xing Song"
date: '2022-10-10'
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.height=6)
pacman::p_load(tidyverse,
               magrittr,
               devtools
               )
source_url("https://raw.githubusercontent.com/sxinger/utils/master/plot_util.R")
```


```{r}
aset<-readRDS("C:/repo/R21_PEDS_UC/data/peds_uc_aset.rds") %>%
  filter(INDEX_YEAR >= 2010 & INDEX_YEAR <= 2020) %>%
  filter(AGE_AT_INDEX <= 17 & AGE_AT_INDEX>=4)

denom<-aset %>% group_by(INDEX_YEAR) %>%
  summarise(NN_YR = length(unique(PATID)),.groups = "drop")
```


## Treatment data completeness

```{r}
endpt<-aset %>% 
  select(PATID,INDEX_YEAR,mesalazine,corticosteroids,immunomodulator, biologics, colectomy) %>%
  mutate(standard = pmin(mesalazine,corticosteroids,na.rm=T)) %>%
  select(PATID, INDEX_YEAR, standard,immunomodulator, biologics, colectomy) %>%
  gather(var,val,-PATID, -INDEX_YEAR) %>%
  filter(!is.na(val)) %>%
  group_by(PATID, INDEX_YEAR) %>%
  mutate(ord = order(val)) %>%
  ungroup 

endpt_summ<-endpt %>%
  filter(ord==1) %>%
  group_by(INDEX_YEAR) %>%
  mutate(N_YR = length(unique(PATID))) %>%
  ungroup %>%
  group_by(INDEX_YEAR,N_YR,var) %>%
  summarise(n_yr=length(unique(PATID)),
            .groups = "drop") %>%
  mutate(p_yr = round(n_yr/N_YR,3)) 

endpt_summ2<-endpt_summ %>%
  bind_rows(
    endpt_summ %>%
      select(INDEX_YEAR,N_YR) %>%
      mutate(n_yr = N_YR) %>%
      left_join(denom,by="INDEX_YEAR") %>%
      mutate(N_YR = NN_YR,
             p_yr = round(n_yr/N_YR,3),
             var = "any") %>%
      unique %>%
      select(-NN_YR)
  )
```


```{r}
ggplot(endpt_summ2 %<>%
         mutate(new_col = convert_scale(p_yr,N_YR)[["val"]],
                axis_formula = convert_scale(p_yr,N_YR)[["formula"]]),
       aes(x=INDEX_YEAR)) +
  geom_col(aes(y=N_YR), size = 1, fill = "grey")+
  geom_line(aes(y=new_col,color=var,group=var), size = 1.5)+
  scale_y_continuous(sec.axis = sec_axis(as.formula(endpt_summ2$axis_formula[1]), name = "proportion"))+
  scale_x_discrete(limits=2010:2020, labels = 2010:2020)+
  theme(axis.text.x = element_text(angle = 80),text=element_text(face="bold"))+
  facet_wrap(~var,ncol=3)
```


## Baseline covariate data completeness

```{r}
var_ind<-c("BMI_ind","hemoglobin_ind","platelet_count_ind","leukocyte_ind","ESR_ind",
           "CRP_ind","albumin_ind","25_OH_VD_ind")

df<-aset %>% 
  select(c("PATID","INDEX_YEAR",var_ind)) %>%
  gather(var,val,-PATID, -INDEX_YEAR) %>%
  group_by(INDEX_YEAR) %>%
  mutate(N_YR = length(unique(PATID))) %>%
  ungroup %>%
  group_by(INDEX_YEAR,N_YR,var) %>%
  summarise(n_yr=sum(val),
            .groups = "drop") %>%
  mutate(p_yr = round(n_yr/N_YR,3)) 

```


```{r}
ggplot(df %<>%
         mutate(new_col = convert_scale(p_yr,N_YR)[["val"]],
                axis_formula = convert_scale(p_yr,N_YR)[["formula"]]),
       aes(x=INDEX_YEAR)) +
  geom_col(aes(y=N_YR), size = 1, fill = "grey")+
  geom_line(aes(y=new_col,color=var,group=var), size = 1.5)+
  theme(axis.text.x = element_text(angle = 80),text=element_text(face="bold")) +
  scale_y_continuous(sec.axis = sec_axis(as.formula(endpt_summ2$axis_formula[1]), name = "proportion"))+
  scale_x_discrete(limits=2010:2020, labels = 2010:2020)+
  facet_wrap(~var,ncol=3)
```

